### ISSUE TITLE
BUG: sanity lock / sync gets stuck on crash

### ISSUE THREAD

**Issue by kfo2010** [arionum/node#10]
I have been writing a bash script to manage a node and I think what is happening occasionally is if node is syncing and nginx or php-fpm or mysql on my node go down OR are restarted, tmp/sanity-lock file remains which prevents my node from syncing further. It gets stuck at whatever block it was on before the service went down. I havent dove deep into code so I might be mis-understading the full flow. 

**If i am missing something here, is there an easy way to reset the lock/sync/queue?** 
I was deleting lock file and resetting sanity_last config in database to 0 after i restart services (nginx, php-fpm, mysql) which seems to work ok and in my bash script its just a simple... 
 `# bash aronode mainnet restart`

**Comment by arionum** [comment]
Fixed in 0.4 due to bootstraipping
