### ISSUE TITLE
BUG: Fresh install; stuck at block 10801

### ISSUE THREAD

**Issue by kfo2010** [arionum/node#11]
Just did a fresh install and seem to be stuck at block 10801.
Nothing in php/nginx error logs.
Syncing fine until it hit 10801

Ubuntu 16, Nginx, Php-fpm, MariaDB. 1GB RAM, 1 CPU VPS.

Not sure but Is issue that server is too small? If so, there needs to be some sort of alert/log telling user so. I have a second node thats been running for a while that is synced. It has 2GB of RAM. 1 CPU. 

If minimum requirements are 2GB of RAM then in my bash setup script I am working on I can check for 2GB of RAM and tell user not enough if less. Thoughts on how to present this requirement to a new user?

Maybe on homepage of node, check for minimum requirements and notify user. Instead of saying "System Check complete" give a breif diagnostic summary. I'd like to see more information on the node homepage personally. This page is first thing new node runners see. It should blow them away. Personally, I love this simple clean design but add more stats to it. [https://aro.pxgamer.xyz/](https://aro.pxgamer.xyz/)

**Comment by owenvoke** [comment]
Interesting, that's the block immediately after the ["Resistance" hard fork][hard-fork] that occurred. 🤔 In theory this shouldn't really have any effect.

[hard-fork]: https://github.com/arionum/node/blob/5871417c4b980018c48dfe9e4dee1520b8dca763/README.md

**Comment by arionum** [comment]
Implemented in 0.4 to check for 2GB of ram.
