### ISSUE TITLE
SUGGESTION: README.md add hardware requirements 

### ISSUE THREAD

**Issue by kfo2010** [arionum/node#12]
It appears cant sync node past block 10801 unless you have 2GB of RAM. Please add minimum and recommended server requirements to README.md. 

This is the first thing new users read. Please add more technical details to the README. A brief description of how the system works would be helpful, who/what its for (PHP Developers to Build Blockchain applications natively). 

And it should give basic overview of how to access and read the /doc/ it's currently a hidden easter egg since no mention of it anywhere. The /doc/ content is good. It should be pointed out as a priority for developers to read first thing. In my bash script I am mentioning this to console on install.

**Comment by arionum** [comment]
Implemented.
Also added a check in the node source for ram.
