### ISSUE TITLE
BUG: sql dump import from alternate node; config hostname wrong

### ISSUE THREAD

**Issue by kfo2010** [arionum/node#14]
if you import a sql dump of the database from another node, the "config" table has the other nodes "hostname" in it. Unless you know this is in there and what it does it will configure your peer with wrong hostname.

I have a fix in my bash script for rebuilding by importing sql file but to others doing this manually its an issue.

After tinkering with this for hours, I am getting timeouts from simple api calls to 127.0.0.1 after an import of pxgamers dump. I updated config hostname to my ip. It syncs fine but cant make any API calls without it hanging constantly. Cant figure out why.

I think what we need is a util.php tool to dump and restore the block chain data. What data tables can we dump and copy from node to node without problems?

**Comment by kfo2010** [comment]
I created a "backup" and a "import" function in my aronode bash script.

In my export I am only exporting "blocks, accounts, transactions, mempool" tables to a sql dump and importing only those tables. It seems to work fine doing this. Do you see any issues with this method that I may be missing?

**Comment by arionum** [comment]
The import should be done after the initial db-schema setup and the config table should be excluded from the dump. I don't see any issues with your method.
