### ISSUE TITLE
SUGGESTION: rename config file to config-sample.inc.php 

### ISSUE THREAD

**Issue by kfo2010** [arionum/node#15]
When doing a git pull instead of relying on .gitignore make a file named config-sample.inc.php. This file stays the same no matter what happens and contains all the recommended defaults. 

Then in code check if config.inc.php exists and if it doesnt tell user to copy the sample and enter in their db details. Then you can always have a copy of the default file for reference. This also allows for user to install with a zip file of the package without using git. This is how wordpress and other frameworks do it. A dummy sample config.

**Comment by owenvoke** [comment]
It may also be worth using a `.env` file for other configuration components as I have done for the RPC.

**Comment by kfo2010** [comment]
Yes. I'd second a .env file which is NOT saved in git but a .env.example is saved in git and always availble like in they do in Laravel.

**Comment by kfo2010** [comment]
This needs to be fixed. I cant run a git pull to update the node without manually renaming my file and then restoring it. ".gitignore only applies to untracked files." so putting this file in .gitignore is useless. the repo should NOT have "config.inc.php" in it since the user edits this. The repo should not contain any files that the user will change. User should get a "config-sample.inc.php" from repo during initial clone and then rename it manually with their own data so it's ignored by future updates via git.

**Comment by owenvoke** [comment]
@KyleFromOhio, you can always make a pull request to rename this and add the changes to the README. 🙂 Then we can see what @arionum thinks about the change. 👍

**Comment by kfo2010** [comment]
True, Im super busy with a number of unrelated things right now. Including making time for the fork this weekend. 

Here is my bandaid fix in my aronode bash script.
mv $DOMAINROOT/include/config.inc.php $DOMAINROOT/include/config.inc.BACKUP.php
git pull origin master
mv $DOMAINROOT/include/config.inc.BACKUP.php $DOMAINROOT/include/config.inc.php

**Comment by arionum** [comment]
Implemented now.
