### ISSUE TITLE
BUG: cant run util.php outside webroot

### ISSUE THREAD

**Issue by kfo2010** [arionum/node#16]
i should be able to run this from console...

`php -f /var/www/mynode.com/util.php current`

it doesnt even error. It just outputs nothing. You have to be in the webroot directory to run util.php.

The problem is include paths are relative. A full path to web directory should be determined in a bootstrap and loaded properly via full path.

require_once("include/init.inc.php");

**Comment by owenvoke** [comment]
I've done this in my node source because it was really annoying me. Just needs a simple `__DIR__`. :+1:

**Comment by owenvoke** [comment]
Well, I'm going to make a PR for this soon. :+1:

**Comment by kfo2010** [comment]
I may take this on later. I'm refactoring wallet cli now so learning the ins and outs of the api, testing , and finding issues/bugs/etc. Need refactoring everywhere. Will take on node files eventually. :)

**Comment by arionum** [comment]
Implemented.
