### ISSUE TITLE
Add tags for the different releases

### ISSUE THREAD

**Issue by owenvoke** [arionum/node#19]
I suggest that we should add tags for versions. It would be easier to manage and allow downloading releases at a specific version for scripts, etc.

I've listed the latest commits for each version below.

Tag | Reference
------ | -------
v0.1a | 50ed36734dc2a2702c1ea9d1283f6dc99c866882
v0.2b | 66dee6516a17daa0872b835a45f5a7ac4282f84a
v0.3.0 | 3a4aaf973c6085c17c0fc193b653a055bf80245e (the latest for now as there is no real versioning in place...)

---------

This should be fine to do using:
```bash
git tag -s v0.1a 50ed36734dc2a2702c1ea9d1283f6dc99c866882
git tag -s v0.2b 66dee6516a17daa0872b835a45f5a7ac4282f84a
git tag -s v0.3.0 3a4aaf973c6085c17c0fc193b653a055bf80245e
git push --tags
```

Which gives you a list like the following ([link](https://prntscr.com/jxnnwr)):

![Releases](https://image.prntscr.com/image/t-fQg-M3TTy6s-K6mHaSeQ.png)

_If you have a GPG key, I've added the usage of `-s` for signing. Which is advised for tags._

**Comment by arionum** [comment]
Implemented. Thanks!
