### ISSUE TITLE
ENHANCEMENT: move initial/boot peers list to config

### ISSUE THREAD

**Issue by kfo2010** [arionum/node#24]
**PROBLEM:** 
sanity.php ...
$f = file("https://www.arionum.com/peers.txt");

This makes the peers list dependent on a central domain arionum.com. The nodes should not be dependent on any calls to arionum.com.

**SOLUTION:**
Create an array in the main config file to allow someone to enter a list of known/custom peers. The sample config would have whats listed in https://www.arionum.com/peers.txt but would allow a user to change them.

**CAVEATS:**
Since users configs are not overwritten by updates, i think it does make sense to use https://www.arionum.com/peers.txt for now as the backup for a user that does not have this new config array set. The default should be to use the central domain but allow user to override it in config with custom list.

**Comment by owenvoke** [comment]
Starting development on this.

**Relevant lines:**
https://github.com/arionum/node/blob/754017f634e939b0d56c0337c10e846c99f705b0/sanity.php#L268-L277
