### ISSUE TITLE
BUG: sanity lock orphaned

### ISSUE THREAD

**Issue by kfo2010** [arionum/node#26]
**PROBLEM:** 
If any of the services go down (php fpm, nginx/apache/mysql), restart, upgrade, or just crash... Maybe even from a reboot or unatended upgrades... it is possible that the sanity-lock file can be orphaned, preventing sanity runs to keep node in sync.

**SOLUTION:** 
IDEA: maybe check the modified date using filemtime() of sanity-lock file. If its older than 3X the "sanity_interval" from config then do an additional check to see if php sanity.php process is running (by looking at the process list) on the system. If it is not running then unlink( sanity-lock ).

**Comment by owenvoke** [comment]
I think that solution seems pretty logical. :+1:

**Comment by owenvoke** [comment]
Looking at this, it is currently in the code, but uses a time of 1 day.

https://github.com/arionum/node/blob/88f50fcae123a887fa804108165ee9bd6fb6ce66/sanity.php#L43-L47

This should be possible to easily implement by moving the `require_once` usage for `init.inc.php` to line 34 (before the sanity lock check) and then utilising the config array value.

https://github.com/arionum/node/blob/88f50fcae123a887fa804108165ee9bd6fb6ce66/sanity.php#L63

----

Started development on this change. See my feature branch:
https://github.com/arionum/node/compare/master...pxgamer:feature/sanity-orphan
