### ISSUE TITLE
Suggestions for V 0.3

### ISSUE THREAD

**Issue by xberg** [arionum/node#40]
(sorry, moving to the correct tab hopefully)

**Comment by owenvoke** [comment]
Is this meant to be empty? 🤔 In the history, I see that the contents was replaced. Is this meant to have the list in it?

**Comment by ProgrammerDan** [comment]
I believe it was opened in error and can be closed.

**Comment by owenvoke** [comment]
@ProgrammerDan Ah, I wasn't sure if the PR (#39) was meant to be replaced by this issue. As this says `moving to the correct tab` but the PR says `moved to issue tab`. Wasn't sure which is intended to be closed.

**Comment by ProgrammerDan** [comment]
Both! :)
