### ISSUE TITLE
SUGGESTION: change default timezone on node to UTC

### ISSUE THREAD

**Issue by kfo2010** [arionum/node#9]
Recommend changing "date_default_timezone_set("Europe/Amsterdam");" to "UTC".

**Comment by owenvoke** [comment]
This seems good to me. Or just have it in the config. Perhaps with UTC as the default value?

I think this was mentioned as a comment in the actual file?

**Comment by kfo2010** [comment]
its in include/init.inc.php its actively set to Amsterdam. Adding to config I agree with with a default set to UTC.

**Comment by arionum** [comment]
I prefer to have all the nodes on the same timezone. Otherwise, they would produce different results.

**Comment by owenvoke** [comment]
What different results would they produce? 🙂 The only thing I can see that is using the date function is logging.

The majority of the functionality in Arionum seems to use the `time()` function which uses UTC as it is epoch.

**Comment by kfo2010** [comment]
Different results because of the timezone settings? Then this is a HUGE problem/issue. The blockchain data should not be using the systems/mysql/ or php timezone as its timestamp reference. It shouldnt care what the timezone of the server is. All data should in blockchain should be set to UTC. Only thing the timezone should be used for is for display to user somewhere to local time (system/mysql/php.ini) converted from UTC.

**Comment by arionum** [comment]
Implemented in 0.4 with UTC as default.
